### PR TITLE
Added the following flink operator tests: MaterializedGroupByOperator, SortOperator, UnionAllOperator

### PR DESCRIPTION
**Pull request by damik3**
Note that the FlinkMaterializedGroupByOperatorTest, although it succeeds, it produces the following messages:

[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/C:/Users/Mike/.m2/repository/com/esotericsoftware/kryo/kryo/2.24.0/kryo-2.24.0.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
[ERROR] WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.util.UnsafeUtil
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release

These are also produced by its respective Spark test, SparkMaterializedGroupByOperatorTest.

### CODE REVIEW

**Review by zkaoudi — CHANGES_REQUESTED** [review]
Thank you Michalis for this PR! 
Can you please add the Apache licence headers in all the new files?

**Comment by zkaoudi** [comment]
Do you think the error/warning comes from the AtomicInteger class that the tests are using?

**Comment by damik3** [comment]
> Thank you Michalis for this PR! Can you please add the Apache licence headers in all the new files?

Oops, just added them!

**Comment by damik3** [comment]
> Do you think the error/warning comes from the AtomicInteger class that the tests are using?

No, I tried it without the AtomicInteger, but it's still there. I also found a discussion [here](https://github.com/EsotericSoftware/kryo/issues/626) and [here](https://github.com/EsotericSoftware/kryo/issues/747), but I don't think it's been solved. The `[ERROR] WARNING` prefix is a bit confusing, but I'd say it's more of a warning.

**Review by zkaoudi — APPROVED** [review]
Since these "errors" are warnings I merge this PR
Thanks @damik3 :)

**Pull request merged**
