### PR TITLE
Remove faulty test from wayang-tensorflow

### PR DESCRIPTION
**Pull request by juripetersen**

### CODE REVIEW

**Comment by zkaoudi** [comment]
Let me remove the docs for now..

**Comment by 2pk03** [comment]
No - that doesn't make it better.  We just need to exclude the directory from a license check

**Comment by zkaoudi** [comment]
Can we bring the changes done by the latest PRs to this one? @juripetersen ?

**Comment by juripetersen** [comment]
> Can we bring the changes done by the latest PRs to this one? @juripetersen ?

Done. The build should run through again.

**Review by zkaoudi — APPROVED** [review]

**Pull request merged**
