### PR TITLE
Refinement of SQL API

### PR DESCRIPTION
**Pull request by kmoltke**
Hi, @michellesackmann and I removed the last hard coded parts of the SQL API.
Everything needed is specified in the model.json file which is located under resources. So, this model.json file is the configuration file like you typically see in other systems. We also added the possibility of specifying a separator for .csv files.

### CODE REVIEW

**Comment by kbeedkar** [comment]
Hi guys, I don't think this is the right way to support different data sources. 

As we discussed in an earlier email, a better way to go about this, which is also extensible and maintainable, is to first extend the WayangRel Algebra, with specific table scan operators (e.g., one for Jdbc, one for csv, etc..) and write logical-to-physical rules. Each physical scan operator should then have methods for accessing sources.

**Comment by 2pk03** [comment]
@kbeedkar can we merge and open a ticket to improve the commit? Multiple CSV files sounds great :)

**Comment by 2pk03** [comment]
> Hi, thank you for your comment. This is something that can be improved, unfortunately, given the limitations of this research project, we don't have resources to do that right now. Also, there are definitely more stuff that could be improved. In our opinion, this PR is still an improvement since it 1) gets rid of all the hard coded parts 2) cuts severely down on the lines of code that the user has to provide to run a query and 3) adds the functionality to provide delimiters/separators for csv-files. Yes, in terms of future maintainability/extensibility we agree with you, but it requires resources that we don't have right now.
> 
> We hope that your suggestions can be implemented in another PR :)

Pls add the license header:
https://github.com/apache/incubator-wayang/actions/runs/4948812486/jobs/8880546014?pr=322#step:3:127

**Comment by kmoltke** [comment]
@2pk03 the license header should be there now :)

**Comment by kbeedkar** [comment]
Yes @2pk03, let's do it that way.

**Review by 2pk03 — APPROVED** [review]
Everything looks good, thank you for this contribution!

**Review by kbeedkar — APPROVED** [review]
Merging this PR as a temporary workaround to support CSV as well Jdbc sources. I will open a ticket for streamlining this further.

**Comment by michellesackmann** [comment]
Sounds great guys, thank you for approving the PR! Is there any chance the PR could be merged before tomorrow afternoon, since we have to hand in the report for our project, and it would be great if it was aligned with what is on the main branch.

**Pull request merged**
