### PR TITLE
Wayang #273 - WebUI Draft

### PR DESCRIPTION
**Pull request by ichbinrich**
As mentioned in #273 the WebUI has been discussed in regards of the design and updated to a more standard layout. This is a draft version, meaning it is not fully connected with Wayang, it requires to develop an intermediate component, wayang-web-dashboard/dashboard-backend. For the moment a synthetic server is provided for User testing purposes. Please refer to the README.md under wayang-web-dashboard/dashboard-webapp

### CODE REVIEW

**Comment by 2pk03** [comment]
Thank you, looks awesome!

**Review by JorgeQuiane — CHANGES_REQUESTED** [review]
Please address the following two points so that we can approve the pull request.

(1) write the right header (only apache license and no DIMA reference/pointer) in the files specified in the error message here: https://github.com/apache/incubator-wayang/actions/runs/4872409321/jobs/8690595686?pr=315

(2) check the license (with rat) of all the third-party libraries that you are using because it seems you are using some with incompatible licences. See here: https://github.com/apache/incubator-wayang/actions/runs/4872409321/jobs/8690595367?pr=315

**Comment by ichbinrich** [comment]
> Please address the following two points so that we can approve the pull request.
> 
> (1) write the right header (only apache license and no DIMA reference/pointer) in the files specified in the error message here: https://github.com/apache/incubator-wayang/actions/runs/4872409321/jobs/8690595686?pr=315
> 
> (2) check the license (with rat) of all the third-party libraries that you are using because it seems you are using some with incompatible licences. See here: https://github.com/apache/incubator-wayang/actions/runs/4872409321/jobs/8690595367?pr=315

Issues were addressed, now all checks have passed. Is there something else to be done?

**Comment by 2pk03** [comment]
@JorgeQuiane can you please review?

**Comment by JorgeQuiane** [comment]
Thanks a lot for the changes!

**Comment by JorgeQuiane** [comment]
Requested changes were correctly done!

**Pull request merged**
