### PR TITLE
Initial version of the SQL API

### PR DESCRIPTION
**Pull request by kbeedkar**
- This initial version of the SQL API supports simple Select-Project Queries over Databases and Java Platform.
- SQL support is based on Apache Calcite

### CODE REVIEW

**Review by 2pk03 — CHANGES_REQUESTED** [review]
License headers are missed in:
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangFilterVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangJoinVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangProjectVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelNodeVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangTableScanVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/optimizer/Optimizer.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/optimizer/WayangProgram.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rel/WayangFilter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rel/WayangJoin.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rel/WayangProject.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rel/WayangTableScan.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rules/WayangRules.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/schema/SchemaUtils.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/schema/WayangSchema.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/schema/WayangSchemaBuilder.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/schema/WayangTable.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/schema/WayangTableBuilder.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/schema/WayangTableStatistic.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/utils/PrintUtils.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/sources/fs/CsvRowConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/sources/fs/JavaCSVTableSource.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlAPI.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlTest.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

**Comment by 2pk03** [comment]
Hey @kbeedkar ,

awesome contribution, thank you! SQL implementation with Apache Calcite is upmost important. Please check the license issues, and re-submit your PR. Codewise everything is fine, I could compile on Mac M1.

**Comment by kbeedkar** [comment]
Hi @Alex, Fixed the license issues. Pls. check again.

**Comment by 2pk03** [comment]
Strict licence check:
```
Warning:  There are 2 forbidden licenses used:
Warning:  License: 'iCal4j - License' used by 1 dependencies:
 -ical4j (org.mnode.ical4j:ical4j:1.0.2 - [http://ical4j.sourceforge.net)](http://ical4j.sourceforge.net%29/)
Warning:  License: 'Public Domain' used by 1 dependencies:
 -Backport of JSR 166 (backport-util-concurrent:backport-util-concurrent:3.1 - http://backport-jsr166.sourceforge.net/)
```

This should not be a problem, since Public Domain is a permissive license:
[Public Domain](https://creativecommons.org/licenses/publicdomain/). I'll check why the build check failed.

**Comment by 2pk03** [comment]
@kbeedkar, build failed here, can you please check?

https://github.com/apache/incubator-wayang/actions/runs/4706923589/jobs/8348520563?pr=284#step:7:1981

**Comment by kbeedkar** [comment]
I could now build successfully locally on my machine. Hopefully, there are no more license issues now.

**Review by 2pk03 — APPROVED** [review]
All checks have passed, that's great @kbeedkar! Thank you so much for this contribution, the integration of Apache Calcite is highly anticipated. Upmost important to got this done, kudos!

**Pull request merged**
