### PR TITLE
naive kmeans operator on sparkml

### PR DESCRIPTION
**Pull request by joker-star-l**
I implemented a naive kmeans operator on sparkml, and add two test cases. It is still in development. Maybe you can give me some advice on the code and design. Thanks!

### CODE REVIEW

**Comment by 2pk03** [comment]
Hi @joker-star-l. thank you! The license check failed, please add the proper license header into:

```
wayang-commons/wayang-basic/src/main/java/org/apache/wayang/basic/operators/KMeansOperator.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/mapping/ml/KMeansMapping.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/operators/ml/SparkKMeansOperator.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/plugin/SparkMLPlugin.java
wayang-platforms/wayang-spark/code/test/java/org/apache/wayang/spark/operators/SparkKMeansOperatorTest.java 
```

**Comment by joker-star-l** [comment]
> Hi @joker-star-l. thank you! The license check failed, please add the proper license header into:
> 
> ```
> wayang-commons/wayang-basic/src/main/java/org/apache/wayang/basic/operators/KMeansOperator.java
> wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/mapping/ml/KMeansMapping.java
> wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/operators/ml/SparkKMeansOperator.java
> wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/plugin/SparkMLPlugin.java
> wayang-platforms/wayang-spark/code/test/java/org/apache/wayang/spark/operators/SparkKMeansOperatorTest.java 
> ```

Ok.

**Comment by 2pk03** [comment]
@joker-star-l - thank you! Can you please have a look why the compile check fails: https://github.com/apache/incubator-wayang/actions/runs/6666101299/job/18117721148?pr=356#step:6:4675 ?

**Review by 2pk03 — APPROVED** [review]
Thank you @joker-star-l - and congratulations to your first commit to Wayang! Well done :)

**Comment by joker-star-l** [comment]
> @joker-star-l - thank you! Can you please have a look why the compile check fails: https://github.com/apache/incubator-wayang/actions/runs/6666101299/job/18117721148?pr=356#step:6:4675 ?

Sorry, I forgot to add spark-ml dependency for java8 and I have fix it.

**Pull request merged**
