### PR TITLE
issue #259 enable logging in CsvRowConverter

### PR DESCRIPTION
**Pull request by kamir**
I have added the logging functionality to the CsvRowConverter.

Also added the CsvRowConverterTest.java to test the thing.

Tested with:

mvn compile test -Dlog4j2.level=DEBUG

Shows:
[INFO] -------------------------------------------------------
[INFO] T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.wayang.api.sql.CsvRowConverterTest
**17:16:01.630 [main] INFO org.apache.wayang.api.sql.sources.fs.CsvRowConverter - Decimal value 123.0289 exceeds declared scale (2). Performing rounding to keep the first 2 fractional digits.**
123.03
**17:16:01.642 [main] INFO org.apache.wayang.api.sql.sources.fs.CsvRowConverter - Decimal value 100.120 exceeds declared scale (2). Performing rounding to keep the first 2 fractional digits.**
100.12
100.12
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.82 s - in org.apache.wayang.api.sql.CsvRowConverterTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

**Comment by 2pk03** [comment]
Hi @kamir , the backend build failed by opening a http request: https://github.com/apache/incubator-wayang/actions/runs/6499354215/job/17669477319?pr=355#step:6:987

Can you please check if that's an issue?

**Comment by kamir** [comment]
I try to remember what can cause this problem with a remote URL.

As part of the remote file reader I have added a test which attempts reading a file from an HTTP URL.

The code is in the file: "JavaTextFileSourceTest" lines 100 to 156 (2 functions)
Those may cause a problem during the testing.

I would be happy to fix that by using proper http(s)-URLs which can be reached during the build run.

Do you have an idea, which URL this could be?

**Comment by kamir** [comment]
Unfortunately I mixed two contributions into one PR.

**Comment by kamir** [comment]
I was tooo late looking into the logs ....
"The logs for this run have expired and are no longer available."

Would you please trigger the action again and reproduce the problem so that I can investigate.

Cheers,
Mirko

**Comment by 2pk03** [comment]
@kamir - can you please check?

**Comment by kamir** [comment]
This PR has been replaced. 
CLOSED for clarity.

**Pull request closed without merging**
