### PR TITLE
Add maven wrapper to ease the development

### PR DESCRIPTION
**Pull request by CalvinKirs**
Add maven wrapper that can ease the development (they don't need to install maven as long as they have Java environment), and we can lock the maven version so that there is no version issues in the future.

### CODE REVIEW

**Comment by berttty** [comment]
Is it possible to do it without the binary file ? Like just downloading from internet

**Comment by CalvinKirs** [comment]
> Is it possible to do it without the binary file ? Like just downloading from internet

hi, this PR has nothing to do with this.

**Comment by CalvinKirs** [comment]
> > Is it possible to do it without the binary file ? Like just downloading from internet
> 
> hi, this PR has nothing to do with this.

We can see similar functionality in other apache projects like camel.

**Comment by berttty** [comment]
Ok :D

**Pull request merged**
