### PR TITLE
Revert "Bump calcite-core from 1.29.0 to 1.32.0 in /wayang-api/wayang-api-sql"

### PR DESCRIPTION
**Pull request by zkaoudi**
Reverts apache/incubator-wayang#302 to avoid building errors

### CODE REVIEW

**Comment by 2pk03** [comment]
No, its a license check issue. Pls read my comments as I merged.

**Comment by zkaoudi** [comment]
I don't understand what's going on. 
Why now Wayang is not building with the previous version of calcite? It used to, right?

**Comment by kbeedkar** [comment]
Calcite 1.29.0 had no license issues and should build.

**Comment by zkaoudi** [comment]
Well now it's not building and gives the same error about forbidden licences for some strange reason.. Anyone has an idea on how to proceed?

**Comment by 2pk03** [comment]
I raised this question in the general incubator list, no response so far. You can try to revert the latest SQL patch, too, so solve this as a hotfix.

**Comment by zkaoudi** [comment]
Great @2pk03! Let's hope they reply soon..

Which SQL patch you refer to?

**Comment by 2pk03** [comment]
https://github.com/apache/incubator-wayang/pull/310 eventually, that would be the state before bump up Calcite.

**Comment by zkaoudi** [comment]
Ah that's a good point, there is an edit in the pom file.. I will check that. Thanks Alex!

**Comment by zkaoudi** [comment]
Ok, now I understand: PR https://github.com/apache/incubator-wayang/pull/310 adds a new calcite dependency and this fails in the license checks as well. 
So we either revert that PR or we modify the main pom.xml to skip these checks.. 
Which one your prefer?
Both solutions are temporary until we figure out what is really the problem..

**Comment by 2pk03** [comment]
I'd say license check skip or adjust, the license in Calcite is legit, since it's a binary one, it seems. Maybe we can tune the license check [1] to be inline with the current Apache License compatibility [2]?
[1] http://www.mojohaus.org/license-maven-plugin/
[2] https://www.apache.org/legal/resolved.html

**Comment by kmoltke** [comment]
Let me have a look if the SQL part works as intended if we leave out the `calcite-file` dependency. Then we can just remove it. Give me 5 min

**Comment by kbeedkar** [comment]
Note that the calcite file is required for integrating file-based tables (e.g., CSV)

**Comment by kmoltke** [comment]
+1 @kbeedkar  I also just tested that, and it is required..

**Comment by kbeedkar** [comment]
> Ok, now I understand: PR #310 adds a new calcite dependency and this fails in the license checks as well. So we either revert that PR or we modify the main pom.xml to skip these checks.. Which one your prefer? Both solutions are temporary until we figure out what is really the problem..

I'd be in favor of reverting to 1.29.0 (for now) until we figure out a solution.

**Comment by zkaoudi** [comment]
There is no problem with the licences now so I close this PR

**Pull request closed without merging**
