### PR TITLE
Python api

### PR DESCRIPTION
**Pull request by ro-pardo**
Now supports juncture topologies, also reduce the number of sockets used by wayang by nesting python operator functions on the same pipeline.

### CODE REVIEW

**Comment by berttty** [comment]
The pull request have the following issues.

-  have absolute path to your machine
- Change the print to logs records, you can find help [here](https://docs.python.org/3/howto/logging.html)

**Comment by ro-pardo** [comment]
Corrections has been applied

**Comment by berttty** [comment]
I cancel the auto build because they new got in a queue

**Comment by berttty** [comment]
Everything looks ok :D

**Pull request merged**
