### PR TITLE
Add .asf.yaml

### PR DESCRIPTION
**Pull request by CalvinKirs**
.asf.yaml is a configuration file that a project may use to control various features such as notification schemes, website staging, GitHub settings, and Pelican builds.

you can refer to this:https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features

### CODE REVIEW

**Comment by CalvinKirs** [comment]
I added two labels, (you can add the rest if necessary)
At the same time, only squash merge is allowed. (Part of the historical PR merge method is incorrect)

**Comment by berttty** [comment]
So nice, Just a question the homepage not need to be https://wayang.apache.org ? or am I wrong ?

**Comment by CalvinKirs** [comment]
> So nice, Just a question the homepage not need to be https://wayang.apache.org ? or am I wrong ?

Thanks for your correction.
BTW, my current settings are relatively simple, we can add other functions later if necessary.

**Comment by berttty** [comment]
Thank so much :D

**Pull request merged**
