### PR TITLE
[CI]Add CodeQl Check

### PR DESCRIPTION
**Pull request by CalvinKirs**
https://github.com/github/codeql-action

It can help us to automatically check some security issues that may exist in the project

### CODE REVIEW

**Comment by CalvinKirs** [comment]
check result: https://github.com/apache/incubator-wayang/pull/51/checks?check_run_id=4801807926
 http://rubygems-proxy.torquebox.org/releases：This address does not seem to provide https

**Comment by berttty** [comment]
Just a doubt this action follow the notice in the link bellow ?

https://infra.apache.org/github-actions-secrets.html

Or it have some exception ?

**Comment by CalvinKirs** [comment]
> 

Of course, this is officially provided by github.

**Comment by berttty** [comment]
So nice :D

**Pull request merged**
