### PR TITLE
Add wayang-api-json and wayang-api-python to create WayangPlans from python

### PR DESCRIPTION
**Pull request by juripetersen**
This PRs description can be found in one of our blog posts:

https://wayang.apache.org/blog/wayang-python-api

### CODE REVIEW

**Comment by juripetersen** [comment]
This PR will also entail an issue arising with typing. Currently the interchange format between python and wayang is mainly handled by serializing strings and parsing them to the desired type in the udf. It is of course desirable to add type hints to operators that allow the parsing to happen implicitly. The issue will be added after merging the PR.

**Review by 2pk03 — APPROVED** [review]
Thank you @juripetersen, looks good to me, tests passed and compile went smooth through. +1 from me

**Comment by 2pk03** [comment]
@zkaoudi @kbeedkar - pls review too before we merge.

**Comment by kbeedkar** [comment]
looks good to me +1

**Pull request merged**
