### PR TITLE
[CI]Add UT check 

### PR DESCRIPTION
**Pull request by CalvinKirs**
We have used the skywalking-eyes check license head, so we can remove RAT.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
I noticed that we have some check tools that still use the `RAT`, but are not affected by this PR change.

**Comment by ro-pardo** [comment]
@CalvinKirs Hi, seems very well. But it is nice to have the RAT for an early checking of the licenses while developing.
Could you preserve it in addition to your work?

**Comment by CalvinKirs** [comment]
> 

hi, currently we only use it to detect license headers in our Travis CI, but we have used `SkyWalking-Eyes` for detection (I will add check license dep later), its function is more powerful, and the community is very active. So I think we can remove the `RAT`. What do you think?

**Comment by berttty** [comment]
I guess what @ro-pardo is point out, it is when you are working in your local machine, because the `SkyWalking-Eyes` is focusing after you did the push, and the `RAT` it will analyze when your are working in your local machine. 

Do am I wrong @ro-pardo  ??

**Comment by ro-pardo** [comment]
@berttty That is exactly my point. Could it be inconvenient to only check the licenses after the push. Of course is great to add this new function, for sure has many other uses; but i think there is no reason to remove RAT by now.

**Comment by CalvinKirs** [comment]
> @berttty That is exactly my point. Could it be inconvenient to only check the licenses after the push. Of course is great to add this new function, for sure has many other uses; but i think there is no reason to remove RAT by now.

OK, I've restored the RAT, thanks for the reminder.

**Review by berttty — COMMENTED** [review]
Everything looks nice

**Review by ro-pardo — COMMENTED** [review]
Implementation seems correct

**Pull request merged**
